TimeParser interface, DataParser interface, GcParser, SdngParser, удалил дублирование
MayerMax/liquid-log pull request #2
Opened 2018-10-12 12:53 UTC by MayerMax

@ykalemi
@d0k1
@etitov

2018-10-12 13:12 UTC, ykalemi requested changes
Направление отчасти верное, но это только начало.

Не увидел, где именно удалено дублирование. В задаче имелся в виду метод App#main, там есть огромный switch-case.
Может, не все изменения вошли в PR? ParsingMethod проверяется, но нигде не передаётся.

Также, не все парсеры используют новые интерфейсы. По условиям задачи
> Для каждого режима должен быть парсер реализующий соответствующий интерфейс
У вас только 2 реализации TimeParser. DataParser вообще только один. Это условие достаточно важное (вместе с избавлением от дублирования), потому что тогда интерфейс DataParser будет выглядеть иначе

2018-10-12 15:52 UTC, MayerMax commented
@ykalemi, извиняюсь, забыл добавить App#main в реквест. 
Добавил еще реализаций DataParser.

2018-10-12 16:41 UTC, ykalemi reviewed
В целом, выглядит хорошо (я чуть позже ещё посмотрю). А проверяли? Со всеми режимами парсинга, желательно

2018-10-12 16:41 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/AbstractFileDataParser.java
> +public abstract class AbstractFileDataParser implements DataParser {
Не очень уверен в необходимости этого класса. Переиспользования пока никакого нет все равно. Но я не особо против.
Единственное, если его оставить - надо его как-то более осмысленно назвать.

2018-10-12 17:08 UTC, MayerMax commented on src/main/java/ru/naumen/sd40/log/parser/AbstractFileDataParser.java
> +public abstract class AbstractFileDataParser implements DataParser {
@ykalemi , решил ввести этот класс в случае если нужна будет в каком-нибудь парсере зависимость внутрення от файла, который читается, либо чтобы парсить целиком.

2018-10-12 17:08 UTC, MayerMax commented
@ykalemi , локально отрабатывает

2018-10-12 18:55 UTC, ykalemi approved these changes

2018-10-12 19:51 UTC, merged

2018-10-16 07:14 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/TopParser.java
> +public class TopParser extends AbstractFileDataParser
Кстати, тут у вас небольшая хитрость. Для TopParser вы не стали писать TimeParser.
Подумайте, как это можно реализовать